### ISSUE TITLE
What is the form of training data

### ISSUE THREAD

**Issue by fun0515** [junyuchen245/Noise2Void_Weights_Constraint_Keras#1]
Your code tastes good but I'm a little unsure: If constraints are used, there is no need to use masking schemes, so the input and the label of the network is the same noisy image. Right? Please let me know if I understand you wrong.

**Comment by junyuchen245** [comment]
Yep, the input and the target are the same image (noisy image). Btw, I have not tested if this weight constraint can generate the same thing as the original paper described, so there is no guarantee.

**Comment by fun0515** [comment]
Well, I thought the sample_png was the result of weight constraint test, but I think your method works, and I would test it myself. Thank you for your answer

**Comment by junyuchen245** [comment]
The sample_result is indeed the result of my constraint implementation, but I tested it with only the additive Gaussian noise. I was trying to say that I cannot guarantee my implementation will work on other types of noise that were mentioned in their paper. Look luck with your experiments.
